# Generated by Django 3.2.9 on 2021-11-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Введите автора книги', to='catalog.Author', verbose_name='Автор Книги'),
        ),
    ]
